trigger:
  - pipelineTest

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '7.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: DotNetCoreCLI@2
        displayName: 'Restore Dependencies'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: '**/**test*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

  - job: Deploy
    displayName: 'Deploy Artifact'
    dependsOn: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Publish Project'
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          publishWebProjects: false
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - script: |
          echo "Listing XML files in $(System.DefaultWorkingDirectory):"
          dir $(System.DefaultWorkingDirectory)\**\*.xml
          displayName: 'List XML files'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '**/*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: false
          failTaskOnFailedTests: true