I am trying to set up an Azure pipeline which will run a Selenium test suite. The suite was build in VS2022 with C# and Selenium. The suite runs fine from VS, command line and also Jenkins but we are looking to build it into a release pipeline and this is a test to see how this will work.

The test pipeline appears to work until we reach task - VSTest@2. At this point the process finds the build dll but does not find the tests which are in this file, below is the current code
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'

- task: VSTest@2
  displayName: 'Ticket Shop Tests'
  inputs:
    testAssemblyVer2: '**\TicketShopTestCases.csprojdll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'