trigger:
  - pipelineTest

schedules:
  - cron: "0 5 * * *"
    displayName: Daily build at 6 AM CET
    branches:
      include:
        - 'pipelineTest'
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: |
      set SourceDirectory=$(Build.SourcesDirectory)
      dotnet test --configuration $(buildConfiguration) --logger trx
    displayName: 'dotnet test'
    continueOnError: true

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**/*.png'
      targetFolder: '$(Build.ArtifactStagingDirectory)/Screenshots'
      artifactName: 'Screenshots'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**/*.html'
      targetFolder: '$(Build.ArtifactStagingDirectory)/Reports'
      artifactName: 'Reports'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'TestArtifacts'