trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '7.x'
      includePreviewVersions: true

  - script: dotnet restore
    displayName: 'Restore NuGet packages'

  - script: dotnet build --configuration Release
    displayName: 'Build solution'

  - script: dotnet test --configuration Release --logger trx
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      mergeTestResults: true
      testRunTitle: 'Selenium and Cucumber Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'TestResults'
      publishLocation: 'Container'