trigger:
- master

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core 3.1
    enabled: true
    inputs:
      version: 3.1.x

  - task: DotnetBuild@1
    displayName: Build solution
    enabled: true
    inputs:
      projects: '**/*.csproj'
      configuration: Release

- job: Test
  dependsOn: Build
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core 3.1
    enabled: true
    inputs:
      version: 3.1.x

  - task: Run Tests on BrowserStack@1
    displayName: Run tests on BrowserStack
    enabled: true
    inputs:
      testCommand: 'dotnet test'
      testFiles: 'tests/*.csproj'
      testFramework: 'MSTest'
      testRunner: 'MSTest'
      testResultsFile: '>test-results.xml'
      os: 'Windows'
      browser: 'Chrome'
